# Generated by Django 5.2.8 on 2025-11-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tutor', models.CharField(max_length=20)),
                ('credits', models.IntegerField()),
                ('students', models.IntegerField()),
                ('times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.times')),
            ],
        ),
    ]
