# Generated by Django 5.2.8 on 2025-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.CharField(),
        ),
    ]
